# Form implementation generated from reading ui file 'd:\Git\pyqt-sqlserver-colab\views\main.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.resize(856, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1856, 1600))
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Tab_Views = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.Tab_Views.setEnabled(True)
        self.Tab_Views.setObjectName("Tab_Views")
        self.T_Home = QtWidgets.QWidget()
        self.T_Home.setObjectName("T_Home")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.T_Home)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 1)
        self.LE_User = QtWidgets.QLineEdit(parent=self.T_Home)
        self.LE_User.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LE_User.setObjectName("LE_User")
        self.gridLayout.addWidget(self.LE_User, 2, 0, 1, 1)
        self.L_User = QtWidgets.QLabel(parent=self.T_Home)
        self.L_User.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_User.setObjectName("L_User")
        self.gridLayout.addWidget(self.L_User, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.LE_Pass = QtWidgets.QLineEdit(parent=self.T_Home)
        self.LE_Pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.LE_Pass.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LE_Pass.setObjectName("LE_Pass")
        self.gridLayout.addWidget(self.LE_Pass, 4, 0, 1, 1)
        self.PB_Login = QtWidgets.QPushButton(parent=self.T_Home)
        self.PB_Login.setObjectName("PB_Login")
        self.gridLayout.addWidget(self.PB_Login, 6, 0, 1, 1)
        self.L_Pass = QtWidgets.QLabel(parent=self.T_Home)
        self.L_Pass.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_Pass.setObjectName("L_Pass")
        self.gridLayout.addWidget(self.L_Pass, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.Tab_Views.addTab(self.T_Home, "")
        self.verticalLayout.addWidget(self.Tab_Views)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Tab_Views.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bar Billar"))
        self.L_User.setText(_translate("MainWindow", "Usuario"))
        self.PB_Login.setText(_translate("MainWindow", "Entrar"))
        self.L_Pass.setText(_translate("MainWindow", "Contraseña"))
        self.Tab_Views.setTabText(self.Tab_Views.indexOf(self.T_Home), _translate("MainWindow", "Inicio"))
