# Form implementation generated from reading ui file 'd:\Git\pyqt-sqlserver-colab\views\forms\DetalleCompra.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_F_Compra(object):
    def setupUi(self, F_Compra):
        F_Compra.setObjectName("F_Compra")
        F_Compra.resize(686, 492)
        self.verticalLayout = QtWidgets.QVBoxLayout(F_Compra)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=F_Compra)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_1 = QtWidgets.QTableWidget(parent=self.groupBox_4)
        self.tableWidget_1.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(0)
        self.tableWidget_1.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_1)
        self.actualizar = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.actualizar.setObjectName("actualizar")
        self.verticalLayout_2.addWidget(self.actualizar)
        self.verticalLayout.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_5 = QtWidgets.QGroupBox(parent=F_Compra)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.groupBox_5)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_2)
        self.verticalLayout.addWidget(self.groupBox_5)

        self.retranslateUi(F_Compra)
        QtCore.QMetaObject.connectSlotsByName(F_Compra)

    def retranslateUi(self, F_Compra):
        _translate = QtCore.QCoreApplication.translate
        F_Compra.setWindowTitle(_translate("F_Compra", "Form"))
        self.groupBox_4.setTitle(_translate("F_Compra", "Lista de compras"))
        self.actualizar.setText(_translate("F_Compra", "Actualizar"))
        self.groupBox_5.setTitle(_translate("F_Compra", "Detalles de compra"))
