# Form implementation generated from reading ui file 'd:\Git\pyqt-sqlserver-colab\views\forms\HorarioEmpleado.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_F_HorarioEmpleado(object):
    def setupUi(self, F_HorarioEmpleado):
        F_HorarioEmpleado.setObjectName("F_HorarioEmpleado")
        F_HorarioEmpleado.resize(792, 537)
        self.verticalLayout = QtWidgets.QVBoxLayout(F_HorarioEmpleado)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=F_HorarioEmpleado)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.id_empleado = QtWidgets.QComboBox(parent=self.groupBox)
        self.id_empleado.setObjectName("id_empleado")
        self.horizontalLayout.addWidget(self.id_empleado)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=F_HorarioEmpleado)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.id_turno = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.id_turno.setObjectName("id_turno")
        self.horizontalLayout_2.addWidget(self.id_turno)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.PB_Limpiar = QtWidgets.QPushButton(parent=F_HorarioEmpleado)
        self.PB_Limpiar.setObjectName("PB_Limpiar")
        self.verticalLayout.addWidget(self.PB_Limpiar)
        self.PB_Guardar = QtWidgets.QPushButton(parent=F_HorarioEmpleado)
        self.PB_Guardar.setObjectName("PB_Guardar")
        self.verticalLayout.addWidget(self.PB_Guardar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_4 = QtWidgets.QGroupBox(parent=F_HorarioEmpleado)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.groupBox_4)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_4.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.PB_Actualizar = QtWidgets.QPushButton(parent=F_HorarioEmpleado)
        self.PB_Actualizar.setObjectName("PB_Actualizar")
        self.verticalLayout.addWidget(self.PB_Actualizar)
        self.PB_Editar = QtWidgets.QPushButton(parent=F_HorarioEmpleado)
        self.PB_Editar.setObjectName("PB_Editar")
        self.verticalLayout.addWidget(self.PB_Editar)
        self.PB_Eliminar = QtWidgets.QPushButton(parent=F_HorarioEmpleado)
        self.PB_Eliminar.setObjectName("PB_Eliminar")
        self.verticalLayout.addWidget(self.PB_Eliminar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(F_HorarioEmpleado)
        QtCore.QMetaObject.connectSlotsByName(F_HorarioEmpleado)

    def retranslateUi(self, F_HorarioEmpleado):
        _translate = QtCore.QCoreApplication.translate
        F_HorarioEmpleado.setWindowTitle(_translate("F_HorarioEmpleado", "Form"))
        self.groupBox.setTitle(_translate("F_HorarioEmpleado", "Empleado"))
        self.groupBox_2.setTitle(_translate("F_HorarioEmpleado", "Turno"))
        self.PB_Limpiar.setText(_translate("F_HorarioEmpleado", "Limpiar"))
        self.PB_Guardar.setText(_translate("F_HorarioEmpleado", "Guardar"))
        self.groupBox_4.setTitle(_translate("F_HorarioEmpleado", "Listado de horarios de empleados"))
        self.PB_Actualizar.setText(_translate("F_HorarioEmpleado", "Actualizar"))
        self.PB_Editar.setText(_translate("F_HorarioEmpleado", "Editar"))
        self.PB_Eliminar.setText(_translate("F_HorarioEmpleado", "Eliminar"))
