# Form implementation generated from reading ui file 'd:\Git\pyqt-sqlserver-colab\views\forms\MesaBillar.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_F_MesaBillar(object):
    def setupUi(self, F_MesaBillar):
        F_MesaBillar.setObjectName("F_MesaBillar")
        F_MesaBillar.resize(792, 555)
        self.verticalLayout = QtWidgets.QVBoxLayout(F_MesaBillar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=F_MesaBillar)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.estado = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.estado.setObjectName("estado")
        self.horizontalLayout_2.addWidget(self.estado)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.PB_Limpiar = QtWidgets.QPushButton(parent=F_MesaBillar)
        self.PB_Limpiar.setObjectName("PB_Limpiar")
        self.verticalLayout.addWidget(self.PB_Limpiar)
        self.PB_Guardar = QtWidgets.QPushButton(parent=F_MesaBillar)
        self.PB_Guardar.setObjectName("PB_Guardar")
        self.verticalLayout.addWidget(self.PB_Guardar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_4 = QtWidgets.QGroupBox(parent=F_MesaBillar)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.groupBox_4)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_4.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.PB_Actualizar = QtWidgets.QPushButton(parent=F_MesaBillar)
        self.PB_Actualizar.setObjectName("PB_Actualizar")
        self.verticalLayout.addWidget(self.PB_Actualizar)
        self.PB_Editar = QtWidgets.QPushButton(parent=F_MesaBillar)
        self.PB_Editar.setObjectName("PB_Editar")
        self.verticalLayout.addWidget(self.PB_Editar)
        self.PB_Eliminar = QtWidgets.QPushButton(parent=F_MesaBillar)
        self.PB_Eliminar.setObjectName("PB_Eliminar")
        self.verticalLayout.addWidget(self.PB_Eliminar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(F_MesaBillar)
        QtCore.QMetaObject.connectSlotsByName(F_MesaBillar)

    def retranslateUi(self, F_MesaBillar):
        _translate = QtCore.QCoreApplication.translate
        F_MesaBillar.setWindowTitle(_translate("F_MesaBillar", "Form"))
        self.groupBox_2.setTitle(_translate("F_MesaBillar", "Estado"))
        self.PB_Limpiar.setText(_translate("F_MesaBillar", "Limpiar"))
        self.PB_Guardar.setText(_translate("F_MesaBillar", "Guardar"))
        self.groupBox_4.setTitle(_translate("F_MesaBillar", "Listado de mesas"))
        self.PB_Actualizar.setText(_translate("F_MesaBillar", "Actualizar"))
        self.PB_Editar.setText(_translate("F_MesaBillar", "Editar"))
        self.PB_Eliminar.setText(_translate("F_MesaBillar", "Eliminar"))
