# Form implementation generated from reading ui file 'd:\Git\pyqt-sqlserver-colab\views\forms\Turno.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_F_Turno(object):
    def setupUi(self, F_Turno):
        F_Turno.setObjectName("F_Turno")
        F_Turno.resize(792, 537)
        self.verticalLayout = QtWidgets.QVBoxLayout(F_Turno)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=F_Turno)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nombre_turno = QtWidgets.QLineEdit(parent=self.groupBox)
        self.nombre_turno.setObjectName("nombre_turno")
        self.horizontalLayout.addWidget(self.nombre_turno)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=F_Turno)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fecha_inicio = QtWidgets.QDateEdit(parent=self.groupBox_2)
        self.fecha_inicio.setObjectName("fecha_inicio")
        self.horizontalLayout_2.addWidget(self.fecha_inicio)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=F_Turno)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fecha_fin = QtWidgets.QDateEdit(parent=self.groupBox_3)
        self.fecha_fin.setObjectName("fecha_fin")
        self.horizontalLayout_3.addWidget(self.fecha_fin)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.PB_Limpiar = QtWidgets.QPushButton(parent=F_Turno)
        self.PB_Limpiar.setObjectName("PB_Limpiar")
        self.verticalLayout.addWidget(self.PB_Limpiar)
        self.PB_Guardar = QtWidgets.QPushButton(parent=F_Turno)
        self.PB_Guardar.setObjectName("PB_Guardar")
        self.verticalLayout.addWidget(self.PB_Guardar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tableView = QtWidgets.QTableView(parent=F_Turno)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.PB_Actualizar = QtWidgets.QPushButton(parent=F_Turno)
        self.PB_Actualizar.setObjectName("PB_Actualizar")
        self.verticalLayout.addWidget(self.PB_Actualizar)
        self.PB_Editar = QtWidgets.QPushButton(parent=F_Turno)
        self.PB_Editar.setObjectName("PB_Editar")
        self.verticalLayout.addWidget(self.PB_Editar)
        self.PB_Eliminar = QtWidgets.QPushButton(parent=F_Turno)
        self.PB_Eliminar.setObjectName("PB_Eliminar")
        self.verticalLayout.addWidget(self.PB_Eliminar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(F_Turno)
        QtCore.QMetaObject.connectSlotsByName(F_Turno)

    def retranslateUi(self, F_Turno):
        _translate = QtCore.QCoreApplication.translate
        F_Turno.setWindowTitle(_translate("F_Turno", "Form"))
        self.groupBox.setTitle(_translate("F_Turno", "Turno"))
        self.groupBox_2.setTitle(_translate("F_Turno", "Fecha inico"))
        self.groupBox_3.setTitle(_translate("F_Turno", "Fecha fin"))
        self.PB_Limpiar.setText(_translate("F_Turno", "Limpiar"))
        self.PB_Guardar.setText(_translate("F_Turno", "Guardar"))
        self.PB_Actualizar.setText(_translate("F_Turno", "Actualizar"))
        self.PB_Editar.setText(_translate("F_Turno", "Editar"))
        self.PB_Eliminar.setText(_translate("F_Turno", "Eliminar"))
