# Form implementation generated from reading ui file 'd:\Git\pyqt-sqlserver-colab\views\forms\Turno.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_F_Turno(object):
    def setupUi(self, F_Turno):
        F_Turno.setObjectName("F_Turno")
        F_Turno.resize(792, 537)
        self.verticalLayout = QtWidgets.QVBoxLayout(F_Turno)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=F_Turno)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=F_Turno)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.groupBox_2)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=F_Turno)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dateEdit_2 = QtWidgets.QDateEdit(parent=self.groupBox_3)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_3.addWidget(self.dateEdit_2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.pushButton = QtWidgets.QPushButton(parent=F_Turno)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=F_Turno)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tableView = QtWidgets.QTableView(parent=F_Turno)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.pushButton_3 = QtWidgets.QPushButton(parent=F_Turno)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=F_Turno)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=F_Turno)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(F_Turno)
        QtCore.QMetaObject.connectSlotsByName(F_Turno)

    def retranslateUi(self, F_Turno):
        _translate = QtCore.QCoreApplication.translate
        F_Turno.setWindowTitle(_translate("F_Turno", "Form"))
        self.groupBox.setTitle(_translate("F_Turno", "Turno"))
        self.groupBox_2.setTitle(_translate("F_Turno", "Fecha inico"))
        self.groupBox_3.setTitle(_translate("F_Turno", "Fecha fin"))
        self.pushButton.setText(_translate("F_Turno", "Limpiar"))
        self.pushButton_2.setText(_translate("F_Turno", "Guardar"))
        self.pushButton_3.setText(_translate("F_Turno", "Actualizar"))
        self.pushButton_4.setText(_translate("F_Turno", "Editar"))
        self.pushButton_5.setText(_translate("F_Turno", "Eliminar"))
