# Form implementation generated from reading ui file 'd:\Git\pyqt-sqlserver-colab\views\forms\Venta.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_F_Venta(object):
    def setupUi(self, F_Venta):
        F_Venta.setObjectName("F_Venta")
        F_Venta.resize(400, 300)
        self.groupBox = QtWidgets.QGroupBox(parent=F_Venta)
        self.groupBox.setGeometry(QtCore.QRect(50, 40, 120, 80))
        self.groupBox.setObjectName("groupBox")

        self.retranslateUi(F_Venta)
        QtCore.QMetaObject.connectSlotsByName(F_Venta)

    def retranslateUi(self, F_Venta):
        _translate = QtCore.QCoreApplication.translate
        F_Venta.setWindowTitle(_translate("F_Venta", "Form"))
        self.groupBox.setTitle(_translate("F_Venta", "Venta"))
